# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a01fba86c385015ddd409bcf45fbf8340f99a6b9c631fd0b13ad6c3f79ce2da9b38dd376a9dc68933c563572c57f7fb6369f70a7f4cb372e1aff73cbe4404b02

test:
  secret_key_base: 4dd10caab72249c7c5bc00bdb5e28ce650dc6af4e0fc0d033cb1e70d6deb63165dfb5a1c3ad1490f331dd2a89fb572fea4e1aa7abdc7332d6c63c43c02c30231

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
